spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8   # 国际化字符编码
    always-use-message-format: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库驱动
    url: jdbc:mysql://127.0.0.1:3306/spring   # 数据库链接url
    username: root  # 数据库连接用户名
    password: 123456  # 数据库密码
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      enable: true
      initial-size: 5 #   初始化大小
      min-idle: 10 # 最小连接数
      max-active: 20 # 最大连接数
      max-wait: 6000 # 获取连接时的最大等待时间，单位为毫秒
      filter:
        stat:
          log-slow-sql: true  # 是否开启慢sql记录
          slow-sql-millis: 5000 # 定义慢sql的时长
          merge-sql: false # 是否合并多个连接池的监控数据
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      connect-timeout: 1000
      lettuce:
        shutdown-timeout: 100
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          max-wait: -1
          min-idle: 0
  redisson:
    address: redis://localhost:6379
    timeout: 30000
  lifecycle:
    timeout-per-shutdown-phase: "30s"   # 优雅停机超时时间

mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml   # mapper.xml文件地址
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 日志打印方式

server:
  port: 8080  # 端口号
  shutdown: graceful  # 优雅停机

rocketmq:
  name-server: localhost:9876
  consumer:
    group: spring_consumer_group  # 消费者组
    pull-batch-size: 10 # 一次拉取消息最大值
    topic: spring_topic
  producer:
    group: spring_producer_group # 生产者组
    send-message-timeout: 30000 # 发送消息超时时间
    retry-times-when-send-failed: 2 # 同步发送消息失败时重试次数
    retry-times-when-send-async-failed: 2 # 异步发送消息失败时重试次数
    max-message-size: 4096 # 消息最大长度
    compress-message-body-threshold: 4096 # 消息压缩阈值


