spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库驱动
    url: jdbc:mysql://127.0.0.1:3306/spring   # 数据库链接url
    username: root  # 数据库连接用户名
    password: 123456  # 数据库密码
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      connect-timeout: 1000
      lettuce:
        shutdown-timeout: 100
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          max-wait: -1
          min-idle: 0

mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml   # mapper.xml文件地址
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 日志打印方式
